{
 "title": "KEMU Cluster Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(label_node_kubernetes_io_instance_type)"
    }
   },
   {
    "name": "gpu_type",
    "query": {
     "query": "label_values(label_datastrophic_io_gpu_type)"
    }
   },
   {
    "name": "availability_zone",
    "query": {
     "query": "label_values(label_topology_kubernetes_io_zone)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (label_node_kubernetes_io_instance_type,label_datastrophic_io_gpu_type,label_topology_kubernetes_io_zone) (kube_node_labels{label_node_kubernetes_io_instance_type!=\"\", label_node_kubernetes_io_instance_type=~\"$instance_type\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"})",
     "legendFormat": "{{label_datastrophic_io_gpu_type}} - {{label_topology_kubernetes_io_zone}}"
    }
   ]
  },
  {
   "title": "GPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (label_node_kubernetes_io_instance_type,label_datastrophic_io_gpu_type,label_topology_kubernetes_io_zone) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"} *on(node) group_left(label_datastrophic_io_gpu_type,label_topology_kubernetes_io_zone) kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"})",
     "legendFormat": "{{label_datastrophic_io_gpu_type}} - {{label_topology_kubernetes_io_zone}}"
    }
   ]
  },
  {
   "title": "Nodes by Instance Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_node_kubernetes_io_instance_type) (kube_node_labels{label_node_kubernetes_io_instance_type!=\"\", label_node_kubernetes_io_instance_type=~\"$instance_type\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Nodes by Availability Zone",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_topology_kubernetes_io_zone) (kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_node_kubernetes_io_instance_type=~\"$instance_type\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPUs by Device Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"} *on(node) group_left(label_datastrophic_io_gpu_type,label_topology_kubernetes_io_zone) kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}) by (label_datastrophic_io_gpu_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPUs by Availability Zone",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"} *on(node) group_left(label_datastrophic_io_gpu_type,label_topology_kubernetes_io_zone) kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}) by (label_topology_kubernetes_io_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPU Allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} \n  * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(pod, namespace) group_left(node) kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n) \n/ \nsum(\n  kube_node_status_capacity{resource=\"nvidia_com_gpu\"} \n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"} \n  * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(pod, namespace) group_left(node) kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n) \n/ \nsum(\n  kube_node_status_capacity{resource=\"cpu\"} \n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\"} \n  * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(pod, namespace) group_left(node) kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n) \n/ \nsum(\n  kube_node_status_capacity{resource=\"memory\"} \n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} \n  * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(pod, namespace) group_left(node) kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "Allocated GPUs"
    },
    {
     "expr": " sum(\n  kube_node_status_capacity{resource=\"nvidia_com_gpu\"} \n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "Total GPUs"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"} \n  * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(pod, namespace) group_left(node) kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "Allocated CPUs"
    },
    {
     "expr": " sum(\n  kube_node_status_capacity{resource=\"cpu\"} \n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "Total CPUs"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\"} \n  * on(pod, namespace) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(pod, namespace) group_left(node) kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "Allocated Memory"
    },
    {
     "expr": " sum(\n  kube_node_status_capacity{resource=\"memory\"} \n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone) \n    kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\", label_topology_kubernetes_io_zone=~\"$availability_zone\"}\n)",
     "legendFormat": "Total Memory"
    }
   ]
  },
  { "title": "Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (namespace, job_name) (\n    label_replace(\n      kube_pod_info{created_by_kind=\"Job\", created_by_name!=\"\"},\n      \"job_name\", \"$1\", \"created_by_name\", \"(.*)\"\n    )\n    * on(node) group_left(label_datastrophic_io_gpu_type)\n      kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\"}\n  )\n  * on(namespace, job_name) group_left()\n    (kube_job_status_active > 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (namespace, job_name) (\n    label_replace(\n      kube_pod_info{created_by_kind=\"Job\", created_by_name!=\"\"},\n      \"job_name\", \"$1\", \"created_by_name\", \"(.*)\"\n    )\n    * on(node) group_left(label_datastrophic_io_gpu_type)\n      kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\"}\n  )\n  * on(namespace, job_name) group_left()\n    (kube_job_status_succeeded > 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (namespace, job_name) (\n    label_replace(\n      kube_pod_info{created_by_kind=\"Job\", created_by_name!=\"\"},\n      \"job_name\", \"$1\", \"created_by_name\", \"(.*)\"\n    )\n    * on(node) group_left(label_datastrophic_io_gpu_type)\n      kube_node_labels{label_datastrophic_io_gpu_type!=\"\", label_datastrophic_io_gpu_type=~\"$gpu_type\"}\n  )\n  * on(namespace, job_name) group_left()\n    (kube_job_status_failed > 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod status by phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (phase) (\n  kube_pod_status_phase {phase!=\"Pending\"}\n  * on(pod, namespace) group_left(node)\n    kube_pod_info\n  * on(node) group_left(label_datastrophic_io_gpu_type, label_topology_kubernetes_io_zone)\n    kube_node_labels{\n      label_datastrophic_io_gpu_type!=\"\", \n      label_datastrophic_io_gpu_type=~\"$gpu_type\",\n      label_topology_kubernetes_io_zone=~\"$availability_zone\"\n    }\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (phase) (\n  (kube_pod_status_phase{phase=\"Pending\"} > 0)\n  * on(pod, namespace) group_left()\n    (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} > 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods by Availability Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (label_topology_kubernetes_io_zone) (\n  kube_pod_status_phase{phase=\"Running\"}\n  * on(pod, namespace) group_left(node)\n    kube_pod_info\n  * on(node) group_left(label_topology_kubernetes_io_zone)\n    kube_node_labels{\n      label_datastrophic_io_gpu_type!=\"\",\n      label_datastrophic_io_gpu_type=~\"$gpu_type\",\n      label_topology_kubernetes_io_zone=~\"$availability_zone\"\n    }\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}