apiVersion: batch/v1
kind: Job
metadata:
  generateName: a100-training-job-no-affinity-
spec:
  completions: 3
  parallelism: 3
  template:
    metadata:
      annotations:
        pod-complete.stage.kwok.x-k8s.io/delay: "5m"
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: datastrophic.io/gpu-type
                    operator: In
                    values: ["nvidia-a100-80gb"]
                  - key: type
                    operator: In
                    values: ["kwok"]
      tolerations:
        - effect: "NoSchedule"
          key: "kwok.x-k8s.io/node"
          value: "fake"
      containers:
        - name: fake-container
          image: fake-image
          resources:
            requests:
              cpu: 24
              memory: 1100Gi
              nvidia.com/gpu: 8
            limits:
              cpu: 24
              memory: 1100Gi
              nvidia.com/gpu: 8
